### ISSUE TITLE
Home Assistant

### ISSUE THREAD

**Issue by mririgoyen** [Pictogrammers/brand-icons#1]
### Before submitting a new request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Pictogrammers/brand-icons/issues?q=is%3Aissue) to make sure there isn't an existing request for this brand.

### Brand Name

Home Assistant

### Website

https://www.home-assistant.io/

### Official Brand Guidelines

Brand assets can be found here: https://github.com/home-assistant/assets

### Other Comments

I was unable to find license information about the logo itself. Perhaps @frenck or @balloob can help provide that information.

**Comment by balloob** [comment]
You can add the Home Assistant logo to pictogrammers brand icons.

The brand guidelines are here https://design.home-assistant.io/#brand/logo

**Comment by mririgoyen** [comment]
Thank you, @balloob.

Do you have any information on copyright, trademark, or license that the Home Assistant logo is released under?

As part of this library, our goal is to make sure our users know exactly what license each glyph is released under. You can see a couple examples in our LICENSE file: https://github.com/Pictogrammers/brand-icons/blob/main/LICENSE.md

**Comment by balloob** [comment]
Our logo should be used as set out in our guidelines and it's copyright is mine.

**Comment by mririgoyen** [comment]
Added. Thank you for your permission.
