### ISSUE TITLE
ESPHome

### ISSUE THREAD

**Issue by mririgoyen** [Pictogrammers/brand-icons#2]
### Before submitting a new request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Pictogrammers/brand-icons/issues?q=is%3Aissue) to make sure there isn't an existing request for this brand.

### Brand Name

ESPHome

### Website

https://esphome.io/

### Official Brand Guidelines

none

### Other Comments

I was unable to find official logos or license information about said logos from their website. We'll need to do some digging, but perhaps @balloob can help here as well.

**Comment by balloob** [comment]
You can add the ESPHome logo to pictogrammers brand icons.

**Comment by mririgoyen** [comment]
Thank you, @balloob.

Do you know where we can find an official SVG of the ESPHome logo?

Do you have any information on copyright, trademark, or license that the ESPHome logo is released under?

As part of this library, our goal is to make sure our users know exactly what license each glyph is released under. You can see a couple examples in our LICENSE file: https://github.com/Pictogrammers/brand-icons/blob/main/LICENSE.md

**Comment by balloob** [comment]
ESPHome is trademarked by Nabu Casa. The SVG can be found by right clicking the logo on https://esphome.io

**Comment by mririgoyen** [comment]
Added. Thank you for permission!
