### ISSUE TITLE
GitHub

### ISSUE THREAD

**Issue by mririgoyen** [Pictogrammers/brand-icons#5]
### Before submitting a new request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Pictogrammers/brand-icons/issues?q=is%3Aissue) to make sure there isn't an existing request for this brand.

### Brand Name

GitHub

### Website

https://www.github.com

### Official Brand Guidelines

Brand guidelines: https://github.com/logos

**Comment by mririgoyen** [comment]
The GitHub guidelines are a little confusing. They are definitely okay with using the "GitHub logo," however they also state:
> Please don't do these things [...] Use any GitHub artwork without permission.

Because we're not directly using the logo to point back to GitHub but instead redistributing the logo, I feel like we should request permission. I am able to do that through their ticketing support system and have opened ticket [#1679414](https://support.github.com/ticket/personal/0/1679414).

**Comment by mririgoyen** [comment]
GitHub has responded:

> Hi Michael,
> 
> Thanks for reaching out. We are uninterested in allowing our logo(s) to be used in this way.
> 
> Regards,
> GitHub Trust & Safety

Because of this response, we will not add the GitHub logo to Brand Library. Additionally, we will accelerate the GitHub logo's removal from MDI.

**Comment by Polda18** [comment]
So if I want to use the icon for example on a wiki page that talks about the GitHub repository (and possibly links to it), using this library, that's considered as "not allowed"? I get it that general brand logos library for anyone to use in any project may seem scary at first. But I'm sure honest people may not use the logo in a way that harms the brand. Is it really that complicated to get a permission for that? Is it that complicated to place legal restrictions to the logos usage in the library, implied by the permission conditions? Or did they assess that it's just too much of a risk?
